Add QtQuick files to install target
Adding QtQuick files to the install target so that linking the compiled library will work as expected. Without this, attempting to build an qtquick example returns:
```
fatal error: kddockwidgets/DockWidgetQuick.h: No such file or directory
   14 | #include <kddockwidgets/DockWidgetQuick.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Or similar due to missing files.