windows: Fix build due to deleting incomplete type
D:\a\KDDockWidgets\KDDockWidgets\src\core\FloatingWindow.cpp(281): error C2220: the following warning is treated as an error
D:\a\KDDockWidgets\KDDockWidgets\src\core\FloatingWindow.cpp(281): warning C4150: deletion of pointer to incomplete type 'QAbstractNativeEventFilter'; no destructor called